//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_NetFramework.App_Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_NetFramework.App_Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your application description page. 的本地化字符串。
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Graph Connect sample for ASP.NET 4.6 的本地化字符串。
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Graph Connect sample 的本地化字符串。
        /// </summary>
        internal static string App_Name_Short {
            get {
                return ResourceManager.GetString("App_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caller needs to authenticate. 的本地化字符串。
        /// </summary>
        internal static string Error_AuthChallengeNeeded {
            get {
                return ResourceManager.GetString("Error_AuthChallengeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while processing your request. 的本地化字符串。
        /// </summary>
        internal static string Error_Introduction {
            get {
                return ResourceManager.GetString("Error_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in  的本地化字符串。
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get email address 的本地化字符串。
        /// </summary>
        internal static string Graph_GetEmailAddress_Button {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get email address 的本地化字符串。
        /// </summary>
        internal static string Graph_GetEmailAddress_Heading {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose the &lt;b&gt;Get email address&lt;/b&gt; button to get the current user&apos;s email address: 的本地化字符串。
        /// </summary>
        internal static string Graph_GetEmailAddress_Instruction {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current user&apos;s email address 的本地化字符串。
        /// </summary>
        internal static string Graph_GetEmailAddress_Results_Label {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=us-ascii&apos;&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;font-family:calibri&apos;&gt;
        ///&lt;h2&gt;Congratulations!&lt;/h2&gt;
        ///&lt;p&gt;This is a message from the Microsoft Graph Connect Sample. You are well on your way to incorporating Microsoft Graph endpoints in your apps.&lt;/p&gt;&lt;a href=&apos;{0}&apos;&gt;See the photo you just uploaded!&lt;/a&gt;
        ///&lt;h3&gt;What&apos;s next?&lt;/h3&gt;&lt;ul&gt;
        ///&lt;li&gt;Check out &lt;a href=&apos;https://developer.microsoft.com/graph&apos;&gt;developer.microsoft.com/graph&lt;/a&gt; to start buildi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Body_Content {
            get {
                return ResourceManager.GetString("Graph_SendMail_Body_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send email 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Button {
            get {
                return ResourceManager.GetString("Graph_SendMail_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send an email 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Heading {
            get {
                return ResourceManager.GetString("Graph_SendMail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After you get the email address, optionally change the following fields and then choose the &lt;b&gt;Send email&lt;/b&gt; button: 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Instruction {
            get {
                return ResourceManager.GetString("Graph_SendMail_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose the &lt;b&gt;Get email address&lt;/b&gt; button first. 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Message_GetEmailFirst {
            get {
                return ResourceManager.GetString("Graph_SendMail_Message_GetEmailFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipient email addresses, separated by a semicolon 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Recipients_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Recipients_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject of email 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Subject_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent from the 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Subject_Text {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success! Your mail was sent. 的本地化字符串。
        /// </summary>
        internal static string Graph_SendMail_Success_Result {
            get {
                return ResourceManager.GetString("Graph_SendMail_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in with Microsoft 的本地化字符串。
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out 的本地化字符串。
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
    }
}
